import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fsp from "node:fs/promises";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  FEATURE_BRANCH_TYPES,
  checkRepoPath,
  ensureRemoteDevBranch,
  featureBranch,
  featureSlug,
  findFeatureWorktree,
  listFeatureWorktrees,
  listOwnedFeatureBranches,
  normalizeFeatureType,
  provisionWorktree,
  reconcileFeatures,
  reconcileWorktrees,
  runGit,
  teardownWorktree,
  defaultWorktreeBase,
} from "./worktrees.js";
import { describeSpawnError } from "./forge.js";
import { makeFakeForge, type FakeForge } from "./forgefake.test.js";

/**
 * Tests for the worktree lifecycle harness, run against a real throwaway git
 * repo — the local half IS git plumbing, so faking git would prove nothing —
 * with the remote half (fetch, and the `origin/dev` the flow is anchored on)
 * served by the fake forge. No network, no gh binary.
 *
 * Each test builds a fresh repo with a main branch, a commit, a .gitignore
 * matching the real repo's posture (node_modules/ and dist/ ignored), build
 * artifacts in the primary tree that provision must NOT touch, and an
 * `origin/dev` on the fake remote. The managed worktree base is a sibling dir
 * inside the same tmp root, mirroring the default layout.
 *
 * The base fixture is deliberately not an npm package, so provision has no
 * lockfile to install from and every test that only cares about git plumbing
 * stays fast. `makeRepo({ nodePackage: true })` opts into a real one for the
 * tests that need a real install to run, and `buildsOnPrepare` gives that
 * package a `prepare` script the way this repo has one, so the install produces
 * a real build directory too.
 *
 * The tmp root is realpath'd up front: macOS spells os.tmpdir() as /var/...
 * while git reports the /private/var/... realpath, and the module's path
 * comparisons must not be fooled by that (nor the tests').
 */

/** A real npm package whose only dependency is a directory inside the repo, so
 *  a real `npm ci` installs something without ever reaching the network. */
const PKG = { name: "fixture", version: "1.0.0", dependencies: { "fixture-dep": "file:dep" } };
const DEP_PKG = { name: "fixture-dep", version: "1.0.0" };

/** A `prepare` script of the same shape as this repo's own (`tsc && chmod +x
 *  dist/index.js`): an install compiles the package, so a plain `npm ci` writes
 *  a real dist/ as a side effect. It records the directory it ran in, which is
 *  what lets a test prove the dist belongs to the tree it sits in. */
const PREPARE_BUILD =
  "node -e \"const fs=require('fs');fs.mkdirSync('dist',{recursive:true});" +
  "fs.writeFileSync('dist/built.txt',process.cwd())\"";

function run(cwd: string, args: string[]): string {
  const res = spawnSync("git", args, { cwd, encoding: "utf8" });
  if (res.status !== 0) {
    throw new Error(`git ${args.join(" ")} failed (${res.status}): ${res.stderr}`);
  }
  return res.stdout.trim();
}

async function makeRepo(extra: { nodePackage?: boolean; buildsOnPrepare?: boolean } = {}): Promise<{
  root: string;
  repo: string;
  base: string;
  forge: FakeForge;
  /** WorktreeOptions for this repo, wired to the fake forge. */
  opts: { repoPath: string; baseDir: string; run: FakeForge["run"] };
  cleanup: () => Promise<void>;
}> {
  const root = await fsp.realpath(await fsp.mkdtemp(path.join(os.tmpdir(), "co-worktree-")));
  const repo = path.join(root, "repo");
  const base = path.join(root, "worktrees");
  await fsp.mkdir(repo);
  run(repo, ["init", "-q", "-b", "main"]);
  run(repo, ["config", "user.email", "test@test"]);
  run(repo, ["config", "user.name", "test"]);
  run(repo, ["config", "commit.gpgsign", "false"]);
  await fsp.writeFile(path.join(repo, "file.txt"), "hello\n", "utf8");
  await fsp.writeFile(path.join(repo, ".gitignore"), "node_modules/\ndist/\n", "utf8");
  if (extra.nodePackage) {
    // A real, installable npm package. `npm ci` does everything it really does
    // here, including the destructive "empty node_modules first" step that is
    // the whole point, but the one dependency is a local directory so it needs
    // no network and finishes in milliseconds. The lockfile is generated by the
    // local npm rather than hand-written, so it stays right across npm versions.
    const pkg = extra.buildsOnPrepare ? { ...PKG, scripts: { prepare: PREPARE_BUILD } } : PKG;
    await fsp.writeFile(path.join(repo, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
    await fsp.mkdir(path.join(repo, "dep"));
    await fsp.writeFile(path.join(repo, "dep", "package.json"), `${JSON.stringify(DEP_PKG, null, 2)}\n`, "utf8");
    // --ignore-scripts: writing the lockfile runs `prepare` too, and a dist/ built
    // here would collide with the primary tree's own further down. Nothing about
    // what a later `npm ci` does is affected by it.
    const lock = spawnSync("npm", ["install", "--package-lock-only", "--ignore-scripts", "--silent"], {
      cwd: repo,
      encoding: "utf8",
    });
    if (lock.status !== 0) throw new Error(`fixture lockfile generation failed: ${lock.stderr}`);
  }
  run(repo, ["add", "."]);
  run(repo, ["commit", "-q", "-m", "init"]);
  // Build artifacts in the PRIMARY tree. Provision must never link to these and
  // nothing done in a worktree may reach them; several tests assert exactly that.
  await fsp.mkdir(path.join(repo, "node_modules"));
  await fsp.writeFile(path.join(repo, "node_modules", "marker.txt"), "deps\n", "utf8");
  await fsp.mkdir(path.join(repo, "dist"));
  await fsp.writeFile(path.join(repo, "dist", "marker.txt"), "build\n", "utf8");
  // The integration branch lives on the remote; co only ever reads origin/dev.
  const forge = makeFakeForge(repo, { dev: run(repo, ["rev-parse", "main"]) });
  return {
    root,
    repo,
    base,
    forge,
    opts: { repoPath: repo, baseDir: base, run: forge.run },
    cleanup: () => fsp.rm(root, { recursive: true, force: true }),
  };
}

function sha(repo: string, ref: string): string {
  return run(repo, ["rev-parse", ref]);
}

function branchExists(repo: string, branch: string): boolean {
  const res = spawnSync("git", ["show-ref", "--verify", "--quiet", `refs/heads/${branch}`], {
    cwd: repo,
    encoding: "utf8",
  });
  return res.status === 0;
}

/** Add a commit to a branch that has no checkout, with plumbing only — the
 *  "unmerged work whose worktree is gone" state, built without a worktree. */
function commitOnBranch(repo: string, branch: string): void {
  const parent = run(repo, ["rev-parse", branch]);
  const tree = run(repo, ["rev-parse", `${branch}^{tree}`]);
  const sha = run(repo, ["commit-tree", "-p", parent, "-m", "unmerged work", tree]);
  run(repo, ["update-ref", `refs/heads/${branch}`, sha]);
}

test("featureSlug normalizes names and featureBranch gives them a conventional prefix", () => {
  assert.equal(featureSlug("My Fancy Feature!"), "my-fancy-feature");
  assert.equal(featureSlug("auth"), "auth");
  assert.equal(featureSlug("  spaces  and__underscores  "), "spaces-and-underscores");
  assert.equal(featureBranch("My Fancy Feature!"), "feat/my-fancy-feature");
  assert.equal(featureBranch("stale token", "fix"), "fix/stale-token");
  assert.equal(featureBranch("the docs", " DOCS "), "docs/the-docs", "case and space are tolerated");
  // Nothing usable survives: refuse rather than mint `feat/`.
  assert.throws(() => featureSlug("!!!"), /empty slug/);
});

test("a branch type outside the Conventional Commits set is refused, not coerced", () => {
  assert.equal(normalizeFeatureType(undefined), "feat", "the default is feat");
  assert.equal(normalizeFeatureType(""), "feat");
  for (const t of FEATURE_BRANCH_TYPES) assert.equal(normalizeFeatureType(t), t);
  assert.throws(() => normalizeFeatureType("feature"), /unknown branch type/);
  assert.throws(() => normalizeFeatureType("wip"), /unknown branch type/);
  assert.throws(() => featureBranch("x", "nope"), /unknown branch type/);
});

test("defaultWorktreeBase is a sibling of the repo, outside its working tree", () => {
  assert.equal(defaultWorktreeBase("/code/app"), "/code/app-worktrees");
});

test("ensureRemoteDevBranch verifies origin/dev, freshens it, and creates nothing", async () => {
  const { repo, opts, forge, cleanup } = await makeRepo();
  try {
    const mainBefore = sha(repo, "main");
    const res = await ensureRemoteDevBranch(opts);
    assert.equal(res.devRef, "origin/dev");
    assert.equal(sha(repo, "origin/dev"), forge.branches.get("dev"), "the tracking ref was fetched");

    // It creates nothing: no local dev is minted, main is untouched, no checkout.
    assert.ok(!branchExists(repo, "dev"), "co never creates a local dev branch");
    assert.equal(sha(repo, "main"), mainBefore);
    assert.equal(run(repo, ["rev-parse", "--abbrev-ref", "HEAD"]), "main", "no checkout happened");
    assert.ok(!forge.calls.some((c) => /^git (branch|push|checkout)/.test(c)), "read-only on the remote");
  } finally {
    await cleanup();
  }
});

test("ensureRemoteDevBranch refuses cleanly when the remote has no dev branch", async () => {
  const { repo, opts, forge, cleanup } = await makeRepo();
  try {
    forge.branches.delete("dev");
    await assert.rejects(ensureRemoteDevBranch(opts), /no 'origin\/dev' branch on the remote/);
    assert.ok(!branchExists(repo, "dev"), "and it still creates nothing");
  } finally {
    await cleanup();
  }
});

test("provisionWorktree cuts <type>/<slug> from origin/dev and links no build artifacts", async () => {
  const { repo, base, opts, forge, cleanup } = await makeRepo();
  try {
    // Make origin/dev and main genuinely different, so "based off origin/dev"
    // is provable: the remote's dev sits at today's main, then main advances.
    const devSha = forge.branches.get("dev")!;
    await fsp.writeFile(path.join(repo, "file.txt"), "main moved on\n", "utf8");
    run(repo, ["commit", "-qam", "advance main"]);
    const mainSha = sha(repo, "main");
    assert.notEqual(mainSha, devSha);

    const rec = await provisionWorktree(opts, "My Feature");
    assert.equal(rec.branch, "feat/my-feature");
    assert.equal(rec.worktreePath, path.join(base, "my-feature"));
    assert.equal(rec.provisionStatus, "ready");

    // A real checkout on the feature branch, at origin/dev's tip — not main's.
    assert.ok(fs.existsSync(path.join(rec.worktreePath, "file.txt")));
    assert.equal(run(rec.worktreePath, ["rev-parse", "--abbrev-ref", "HEAD"]), rec.branch);
    assert.equal(sha(rec.worktreePath, "HEAD"), devSha);
    // --no-track: the feature branch must not adopt origin/dev as its upstream
    // (git exits 1 for a config key that isn't there, which is the assertion).
    assert.equal(
      spawnSync("git", ["config", "--get", `branch.${rec.branch}.remote`], { cwd: repo }).status,
      1,
      "the feature branch has no upstream of its own",
    );

    // ISOLATION: nothing in the worktree points at the primary's build output.
    // A link here is the defect this module exists to have stopped making.
    for (const name of ["node_modules", "dist"]) {
      const inWorktree = await fsp.lstat(path.join(rec.worktreePath, name)).catch(() => null);
      assert.equal(inWorktree, null, `${name} is not provisioned into the worktree at all`);
      // And the primary's own copy is untouched by any of it.
      assert.equal(
        await fsp.readFile(path.join(repo, name, "marker.txt"), "utf8"),
        name === "dist" ? "build\n" : "deps\n",
      );
    }
    // No lockfile in this fixture, so there is no honest install to run.
    assert.deepEqual(rec.dependencies, { status: "skipped", reason: "no lockfile to install from" });

    assert.equal(sha(repo, "main"), mainSha, "main untouched");
  } finally {
    await cleanup();
  }
});

/**
 * THE REGRESSION. An earlier build symlinked the worktree's node_modules back to
 * the primary tree, and `npm ci` opens by reading node_modules and deleting every
 * entry it finds — through the link, that was the CAPTAIN'S dependencies, gone in
 * one command a crew agent runs as a matter of routine.
 *
 * Deliberately a real `npm ci`, not a fake: the bug lived entirely in what a real
 * package manager does to a real symlink, so anything faked here would pass
 * against the broken code too. The fixture has no dependencies, so it needs no
 * network and the destructive step still runs in full.
 */
test("a crew agent's npm ci in a worktree cannot reach the primary tree's dependencies", async () => {
  const { repo, opts, cleanup } = await makeRepo({ nodePackage: true });
  try {
    const rec = await provisionWorktree(opts, "auth");
    assert.equal(rec.dependencies?.status, "installed", "the repo's own frozen install ran");
    assert.equal(rec.dependencies?.command, "npm ci");

    // What provision left is the worktree's OWN directory, not a link out of it.
    const nm = await fsp.lstat(path.join(rec.worktreePath, "node_modules"));
    assert.ok(nm.isDirectory() && !nm.isSymbolicLink(), "node_modules is the worktree's own dir");

    const res = spawnSync("npm", ["ci"], { cwd: rec.worktreePath, encoding: "utf8" });
    assert.equal(res.status, 0, `npm ci failed: ${res.stderr}`);

    assert.equal(
      await fsp.readFile(path.join(repo, "node_modules", "marker.txt"), "utf8"),
      "deps\n",
      "the primary tree's dependencies survived a crew agent's reinstall",
    );
  } finally {
    await cleanup();
  }
});

/**
 * THE OTHER HALF OF THE SAME REGRESSION. The old build symlinked dist/ back to
 * the primary tree as well, and that link was the quieter of the two faults: a
 * build run in a worktree wrote through it into the primary's dist, which is the
 * dist the captain's installed `co` actually executes, so their tool was
 * silently swapped for unreviewed feature code.
 *
 * Nothing creates that link today, so until this test the property held by
 * omission and nothing said so. It is asserted for BOTH artifacts, because the
 * safe invariant is "never a link out of the worktree", not "always present":
 * a repo with no lockfile gets no node_modules and no build, and that is
 * isolation too.
 *
 * lstat, never stat or existsSync: stat follows a link, so a dist symlinked into
 * the primary tree answers as a perfectly good directory. A check that cannot
 * see the link is not worth running.
 *
 * The fixture's `prepare` mirrors this repo's own (`tsc && chmod +x
 * dist/index.js`), which makes this the live case rather than a hypothetical:
 * provision's frozen install really does build a dist inside the worktree, so a
 * link there would be written through on the very first provision.
 */
test("a freshly provisioned worktree's node_modules and dist are its own, never links out", async () => {
  const { repo, opts, cleanup } = await makeRepo({ nodePackage: true, buildsOnPrepare: true });
  try {
    const rec = await provisionWorktree(opts, "artifacts");
    assert.equal(rec.dependencies?.status, "installed", "the repo's own frozen install ran");

    for (const name of ["node_modules", "dist"]) {
      const st = await fsp.lstat(path.join(rec.worktreePath, name)).catch(() => null);
      if (!st) continue; // absent is fine; linked is not
      assert.equal(st.isSymbolicLink(), false, `${name} is not a symlink out of the worktree`);
      assert.ok(st.isDirectory(), `${name} is the worktree's own directory`);
    }

    // The install ran `prepare`, so the worktree has a real dist — and it is ITS
    // OWN: the build wrote down the tree it ran in, and nothing of the primary's
    // dist is visible through it.
    const dist = path.join(rec.worktreePath, "dist");
    assert.ok(fs.existsSync(dist), "provision's install built a dist inside the worktree");
    const builtIn = (await fsp.readFile(path.join(dist, "built.txt"), "utf8")).trim();
    assert.ok(samePathish(builtIn, rec.worktreePath), `dist was built in ${builtIn}, not the worktree`);
    assert.equal(fs.existsSync(path.join(dist, "marker.txt")), false, "the primary's dist is not visible through it");

    // And the primary tree holds exactly what it held before, both ways round:
    // its own artifacts survived, and the worktree's build did not land in them.
    for (const name of ["node_modules", "dist"]) {
      assert.equal(
        await fsp.readFile(path.join(repo, name, "marker.txt"), "utf8"),
        name === "dist" ? "build\n" : "deps\n",
        `the primary's ${name} is untouched by provisioning a worktree`,
      );
    }
    assert.equal(
      fs.existsSync(path.join(repo, "dist", "built.txt")),
      false,
      "the worktree's build never wrote the primary's dist",
    );
  } finally {
    await cleanup();
  }
});

test("teardown removes the worktree's own build output and never follows a legacy link", async () => {
  const { repo, opts, cleanup } = await makeRepo();
  try {
    // Two features: one provisioned normally, one doctored to look like a
    // worktree the OLD build left behind, symlinks and all. Both must tear down,
    // and neither may take the primary's artifacts with it.
    const own = await provisionWorktree(opts, "own");
    await fsp.mkdir(path.join(own.worktreePath, "node_modules"), { recursive: true });
    await fsp.writeFile(path.join(own.worktreePath, "node_modules", "local.txt"), "mine\n", "utf8");

    const legacy = await provisionWorktree(opts, "legacy");
    for (const name of ["node_modules", "dist"]) {
      await fsp.symlink(path.join(repo, name), path.join(legacy.worktreePath, name), "dir");
    }

    for (const rec of [own, legacy]) {
      const result = await teardownWorktree(opts, rec.feature);
      assert.equal(result.worktreeRemoved, true, `${rec.feature} worktree removed`);
      assert.equal(fs.existsSync(rec.worktreePath), false, `${rec.feature} is gone from disk`);
    }

    for (const name of ["node_modules", "dist"]) {
      assert.equal(
        await fsp.readFile(path.join(repo, name, "marker.txt"), "utf8"),
        name === "dist" ? "build\n" : "deps\n",
        `the primary's ${name} is untouched by teardown`,
      );
    }
  } finally {
    await cleanup();
  }
});

test("provisionWorktree is idempotent for a provisioned feature and rejects half-states", async () => {
  const { repo, opts, cleanup } = await makeRepo();
  try {
    const first = await provisionWorktree(opts, "auth");
    const again = await provisionWorktree(opts, "auth");
    assert.deepEqual(again, first, "re-provisioning an intact feature returns the same record");

    // A leftover branch with no worktree is a half-state: refuse, point at
    // reconcile, and above all don't guess which side to destroy. Both naming
    // schemes count — an old `co/feat-*` ref blocks the same slug.
    run(repo, ["branch", "co/feat-leftover", "main"]);
    await assert.rejects(
      provisionWorktree(opts, "leftover"),
      /is not a feature co provisioned/,
    );
    assert.ok(branchExists(repo, "co/feat-leftover"), "the refusal deleted nothing");
    assert.ok(!branchExists(repo, "feat/leftover"), "and minted no second branch for the slug");
  } finally {
    await cleanup();
  }
});

test("provisionWorktree cuts the type the caller asked for, and refuses one it doesn't know", async () => {
  const { repo, base, opts, cleanup } = await makeRepo();
  try {
    const rec = await provisionWorktree(opts, "Stale Token", { type: "fix" });
    assert.equal(rec.branch, "fix/stale-token");
    assert.equal(rec.worktreePath, path.join(base, "stale-token"), "the dir is the slug, type-free");
    assert.equal(run(rec.worktreePath, ["rev-parse", "--abbrev-ref", "HEAD"]), "fix/stale-token");

    await assert.rejects(provisionWorktree(opts, "nope", { type: "wip" }), /unknown branch type/);
    assert.ok(!fs.existsSync(path.join(base, "nope")), "a bad type creates nothing at all");
  } finally {
    await cleanup();
  }
});

test("ownership is the worktree, not the name: a human's feat/* branch is invisible to every lever", async () => {
  const { root, repo, opts, cleanup } = await makeRepo();
  try {
    // The captain's own branch, named exactly as a feature would be, in their
    // own worktree outside co's managed base.
    const human = path.join(root, "captains-tree");
    run(repo, ["worktree", "add", "-q", human, "-b", "feat/my-feature", "main"]);

    assert.deepEqual(await listFeatureWorktrees(opts), [], "not one of co's worktrees");
    assert.equal(await findFeatureWorktree(opts, "My Feature"), null);
    assert.deepEqual(await listOwnedFeatureBranches(opts), [], "and not one of co's branches");

    // The boot rebuild neither adopts it as a feature nor reports it at all.
    const report = await reconcileFeatures(opts);
    assert.deepEqual(report.records, []);
    assert.deepEqual(report.anomalies, []);

    // Teardown cannot reach it: no worktree of co's, so nothing to remove, and
    // the branch it would consider is the legacy name, which does not exist.
    const t = await teardownWorktree(opts, "My Feature");
    assert.equal(t.worktreeRemoved, false);
    assert.equal(t.branchDeleted, false);
    assert.ok(branchExists(repo, "feat/my-feature"), "the captain's branch is untouched");
    assert.ok(fs.existsSync(path.join(human, "file.txt")), "and so is their checkout");

    // And co will not cut over it either — it refuses instead.
    await assert.rejects(provisionWorktree(opts, "My Feature"), /is not a feature co provisioned/);
    assert.ok(branchExists(repo, "feat/my-feature"));
  } finally {
    await cleanup();
  }
});

test("a legacy co/feat-* worktree stays co's, is never renamed, and tears down on its own branch", async () => {
  const { repo, base, opts, cleanup } = await makeRepo();
  try {
    // What an older build left behind: the checkout at <base>/<slug>, on the
    // old branch name. Nothing marks it but its position.
    await ensureRemoteDevBranch(opts);
    await fsp.mkdir(base, { recursive: true });
    const legacyPath = path.join(base, "prompt-fixes");
    run(repo, ["worktree", "add", "-q", legacyPath, "-b", "co/feat-prompt-fixes", "origin/dev"]);

    const owned = await findFeatureWorktree(opts, "prompt fixes");
    assert.equal(owned?.branch, "co/feat-prompt-fixes", "recognised by its worktree, not its name");
    assert.deepEqual((await listFeatureWorktrees(opts)).map((w) => w.slug), ["prompt-fixes"]);

    // Re-provisioning returns it AS IT IS: no rename, no second branch.
    const rec = await provisionWorktree(opts, "prompt fixes");
    assert.equal(rec.branch, "co/feat-prompt-fixes");
    assert.equal(rec.worktreePath, legacyPath);
    assert.ok(!branchExists(repo, "feat/prompt-fixes"), "no conventional twin was minted");

    // And teardown acts on the branch the worktree actually holds.
    const t = await teardownWorktree(opts, "prompt fixes");
    assert.equal(t.branch, "co/feat-prompt-fixes");
    assert.equal(t.worktreeRemoved, true);
    assert.equal(t.branchDeleted, true, "it is contained in origin/dev, so it is safe to drop");
  } finally {
    await cleanup();
  }
});

test("a branch co cut is still known as co's once its worktree is gone; a lookalike never is", async () => {
  const { repo, opts, cleanup } = await makeRepo();
  try {
    const mine = await provisionWorktree(opts, "orphan");
    run(repo, ["branch", "co/feat-old-one", "main"]); // an older build's leftover
    run(repo, ["branch", "feat/decoy", "main"]); // the captain's, same shape as ours

    // Lose the checkout, keep the branch — the crashed-run case.
    run(repo, ["worktree", "remove", "--force", mine.worktreePath]);

    const owned = (await listOwnedFeatureBranches(opts)).map((o) => o.branch).sort();
    assert.deepEqual(owned, ["co/feat-old-one", "feat/orphan"], "the marker and the legacy prefix, nothing else");

    // The boot rebuild reports the unmerged work and says nothing about the decoy.
    commitOnBranch(repo, "feat/orphan");
    const report = await reconcileFeatures(opts);
    assert.deepEqual(
      report.anomalies.filter((a) => a.kind === "branch-without-worktree").map((a) => a.ref),
      ["feat/orphan"],
    );
    assert.ok(branchExists(repo, "feat/decoy"), "and the captain's branch is left entirely alone");
  } finally {
    await cleanup();
  }
});

test("a worktree base inside the repo working tree is rejected", async () => {
  const { repo, forge, cleanup } = await makeRepo();
  try {
    await assert.rejects(
      provisionWorktree({ repoPath: repo, baseDir: path.join(repo, "wt"), run: forge.run }, "x"),
      /outside the repo working tree/,
    );
  } finally {
    await cleanup();
  }
});

test("teardownWorktree removes the worktree, deletes the merged branch, prunes, and tolerates a repeat", async () => {
  const { repo, opts, cleanup } = await makeRepo();
  try {
    const rec = await provisionWorktree(opts, "done-feature");
    const result = await teardownWorktree(opts, "done-feature");
    assert.equal(result.worktreeRemoved, true);
    assert.equal(result.branchDeleted, true, "a branch still equal to origin/dev is merged, hence deletable");
    assert.ok(!fs.existsSync(rec.worktreePath), "worktree dir is gone");
    assert.ok(!branchExists(repo, rec.branch), "branch is gone");
    const meta = await fsp.readdir(path.join(repo, ".git", "worktrees")).catch(() => []);
    assert.deepEqual(meta, [], "no stale worktree metadata remains");

    // Already removed: a second teardown is a quiet no-op, not an error.
    const repeat = await teardownWorktree(opts, "done-feature");
    assert.equal(repeat.worktreeRemoved, false);
    assert.equal(repeat.branchDeleted, false);
  } finally {
    await cleanup();
  }
});

test("teardownWorktree with keepBranch removes ONLY the checkout — the landed branch ref survives", async () => {
  const { repo, opts, cleanup } = await makeRepo();
  try {
    const rec = await provisionWorktree(opts, "landed");
    await fsp.writeFile(path.join(rec.worktreePath, "work.txt"), "landed work\n", "utf8");
    run(rec.worktreePath, ["add", "work.txt"]);
    run(rec.worktreePath, ["commit", "-qm", "job: work"]);

    // This is what a PR merge's teardown does: the forge merged the branch, so
    // the ref is kept on purpose — regardless of what the local refs think.
    const result = await teardownWorktree(opts, "landed", { keepBranch: true });
    assert.equal(result.worktreeRemoved, true);
    assert.equal(result.branchDeleted, false);
    assert.match(result.branchKeptReason ?? "", /kept by policy/);
    assert.ok(!fs.existsSync(rec.worktreePath));
    assert.ok(branchExists(repo, rec.branch), "the branch ref outlives its worktree");
  } finally {
    await cleanup();
  }
});

test("teardownWorktree keeps a branch with unmerged commits and says why", async () => {
  const { repo, opts, cleanup } = await makeRepo();
  try {
    const rec = await provisionWorktree(opts, "in-progress");
    await fsp.writeFile(path.join(rec.worktreePath, "work.txt"), "unmerged\n", "utf8");
    run(rec.worktreePath, ["add", "work.txt"]);
    run(rec.worktreePath, ["commit", "-qm", "feature work"]);

    const result = await teardownWorktree(opts, "in-progress");
    assert.equal(result.worktreeRemoved, true, "a clean worktree is removable even when ahead");
    assert.equal(result.branchDeleted, false);
    assert.match(result.branchKeptReason ?? "", /not merged into 'origin\/dev'/);
    assert.ok(branchExists(repo, rec.branch), "the unmerged branch survives");
  } finally {
    await cleanup();
  }
});

test("teardownWorktree refuses to destroy uncommitted work", async () => {
  const { repo, opts, cleanup } = await makeRepo();
  try {
    const rec = await provisionWorktree(opts, "dirty");
    await fsp.writeFile(path.join(rec.worktreePath, "wip.txt"), "not committed\n", "utf8");
    await assert.rejects(teardownWorktree(opts, "dirty"), /worktree remove/);
    assert.ok(fs.existsSync(rec.worktreePath), "the dirty worktree is still there");
    assert.ok(branchExists(repo, rec.branch), "and so is its branch");
  } finally {
    await cleanup();
  }
});

test("reconcileWorktrees removes zombie worktrees, keeps dirty work, and deletes no branch at all", async () => {
  const { repo, base, opts, forge, cleanup } = await makeRepo();
  try {
    // A clean provisioned worktree at startup IS the zombie: nothing is in
    // flight, so a crashed run must have left it.
    const zombie = await provisionWorktree(opts, "zombie");
    const dirty = await provisionWorktree(opts, "dirty-one");
    await fsp.writeFile(path.join(dirty.worktreePath, "wip.txt"), "precious\n", "utf8");
    run(repo, ["branch", "keep-me"]); // an unrelated user branch
    const mainSha = sha(repo, "main");
    const devSha = forge.branches.get("dev");

    const report = await reconcileWorktrees({ repoPath: repo, baseDir: base, run: forge.run });
    assert.deepEqual(report.removedWorktrees, [zombie.worktreePath]);
    assert.ok(!fs.existsSync(zombie.worktreePath));
    // Branch refs are kept now that features land by PR: the zombie's checkout
    // is swept, its ref is not.
    assert.deepEqual(report.removedBranches, []);
    assert.ok(branchExists(repo, zombie.branch));
    assert.ok(report.kept.some((k) => k.ref === zombie.branch && /branch refs are kept/.test(k.reason)));

    // The dirty worktree was kept with a reason, its branch untouched.
    assert.ok(report.kept.some((k) => k.ref === dirty.worktreePath && /uncommitted/.test(k.reason)));
    assert.ok(fs.existsSync(path.join(dirty.worktreePath, "wip.txt")));
    assert.ok(branchExists(repo, dirty.branch));

    // Non-co/feat-* refs are outside reconcile's world entirely.
    assert.ok(branchExists(repo, "keep-me"));
    assert.equal(sha(repo, "main"), mainSha);
    assert.equal(forge.branches.get("dev"), devSha, "the remote is untouched");
  } finally {
    await cleanup();
  }
});

test("reconcileWorktrees prunes metadata for a worktree whose directory was deleted", async () => {
  const { repo, base, opts, forge, cleanup } = await makeRepo();
  try {
    const rec = await provisionWorktree(opts, "gone");
    await fsp.rm(rec.worktreePath, { recursive: true, force: true }); // the crash

    const report = await reconcileWorktrees({ repoPath: repo, baseDir: base, run: forge.run });
    assert.deepEqual(report.removedBranches, []);
    assert.ok(branchExists(repo, rec.branch), "the freed branch ref is kept, not swept");
    const meta = await fsp.readdir(path.join(repo, ".git", "worktrees")).catch(() => []);
    assert.deepEqual(meta, [], "stale metadata pruned");
  } finally {
    await cleanup();
  }
});

test("reconcileWorktrees removes a stray dir whose registration was lost, keeps foreign dirs", async () => {
  const { repo, base, opts, forge, cleanup } = await makeRepo();
  try {
    const rec = await provisionWorktree(opts, "stray");
    // Lose the registration but not the directory — the inverse crash of the
    // test above. git no longer lists the worktree; the dir remains.
    await fsp.rm(path.join(repo, ".git", "worktrees", "stray"), { recursive: true, force: true });
    // A foreign dir in the base that is NOT one of our worktrees must survive.
    const foreign = path.join(base, "not-ours");
    await fsp.mkdir(foreign);
    await fsp.writeFile(path.join(foreign, "data.txt"), "hands off\n", "utf8");

    const report = await reconcileWorktrees({ repoPath: repo, baseDir: base, run: forge.run });
    assert.deepEqual(report.removedStrays, [rec.worktreePath]);
    assert.ok(!fs.existsSync(rec.worktreePath));
    assert.deepEqual(report.removedBranches, []);
    assert.ok(fs.existsSync(path.join(foreign, "data.txt")), "foreign dir untouched");
    assert.ok(report.kept.some((k) => k.ref === foreign));
  } finally {
    await cleanup();
  }
});

test("reconcileWorktrees leaves a feature named in keep fully alone", async () => {
  const { repo, base, opts, forge, cleanup } = await makeRepo();
  try {
    const active = await provisionWorktree(opts, "active");
    const report = await reconcileWorktrees(
      { repoPath: repo, baseDir: base, run: forge.run },
      { keep: ["active"] },
    );
    assert.deepEqual(report.removedWorktrees, []);
    assert.deepEqual(report.removedBranches, []);
    assert.ok(report.kept.some((k) => k.ref === active.branch && /in-flight/.test(k.reason)));
    assert.ok(fs.existsSync(active.worktreePath));
    assert.ok(branchExists(repo, active.branch));
  } finally {
    await cleanup();
  }
});

// --- the linked repo ---------------------------------------------------------
//
// checkRepoPath and the ENOENT it exists to stop being mistaken for a broken
// git install. The bug these came from: a repoPath stored with a stray command
// glued onto it, which reached spawn() as a cwd, and every git call in the
// feature layer then failed as `spawn git ENOENT` — the identical error a
// machine with no git produces.

test("runGit reports a missing cwd as a missing directory, not a missing git", async () => {
  const { root, cleanup } = await makeRepo();
  try {
    const gone = path.join(root, "not-a-directory");
    await assert.rejects(
      () => runGit(gone, ["status"]),
      (e: Error) => {
        assert.match(e.message, /working directory does not exist/);
        assert.match(e.message, new RegExp(gone.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
        // The point of the whole exercise: it must not read as a missing binary.
        assert.doesNotMatch(e.message, /no 'git' found on PATH/);
        return true;
      },
    );
  } finally {
    await cleanup();
  }
});

test("describeSpawnError names PATH when the cwd is fine, and passes non-ENOENT through", async () => {
  const { repo, cleanup } = await makeRepo();
  try {
    const missingBinary = Object.assign(new Error("spawn nope ENOENT"), { code: "ENOENT" });
    assert.match(describeSpawnError(missingBinary, "nope", repo).message, /no 'nope' found on PATH/);

    // Anything that is not an ENOENT is somebody else's fault to describe.
    const other = Object.assign(new Error("spawn git EACCES"), { code: "EACCES" });
    assert.equal(describeSpawnError(other, "git", repo), other);
  } finally {
    await cleanup();
  }
});

test("checkRepoPath accepts a repository root", async () => {
  const { repo, cleanup } = await makeRepo();
  try {
    const check = await checkRepoPath(repo);
    assert.equal(check.ok, true);
    assert.ok(check.ok && samePathish(check.repoPath, repo));
  } finally {
    await cleanup();
  }
});

test("checkRepoPath rejects a path that does not exist", async () => {
  const { root, cleanup } = await makeRepo();
  try {
    // Exactly the shape the real fault had: a real repo path with a stray
    // command appended by a prompt that accepted the whole line.
    const check = await checkRepoPath(path.join(root, "repo", "co pane gav-lib"));
    assert.equal(check.ok, false);
    assert.ok(!check.ok && /does not exist/.test(check.reason));
    assert.ok(!check.ok && check.toplevel === undefined);
  } finally {
    await cleanup();
  }
});

test("checkRepoPath rejects a directory that is not a git repository", async () => {
  const { root, cleanup } = await makeRepo();
  try {
    const plain = path.join(root, "plain");
    await fsp.mkdir(plain);
    const check = await checkRepoPath(plain);
    assert.equal(check.ok, false);
    assert.ok(!check.ok && /not a git repository/.test(check.reason));
  } finally {
    await cleanup();
  }
});

test("checkRepoPath rejects a subdirectory of a repo and offers its root", async () => {
  const { repo, cleanup } = await makeRepo();
  try {
    const sub = path.join(repo, "frontend");
    await fsp.mkdir(sub);
    const check = await checkRepoPath(sub);
    assert.equal(check.ok, false);
    assert.ok(!check.ok && /is not its root/.test(check.reason));
    assert.ok(!check.ok && check.toplevel && samePathish(check.toplevel, repo));
    // Why it is refused at all: the managed base would land inside the repo.
    assert.ok(defaultWorktreeBase(sub).startsWith(repo + path.sep));
  } finally {
    await cleanup();
  }
});

/** Compare two paths through realpath — macOS spells tmp both ways. */
function samePathish(a: string, b: string): boolean {
  return fs.realpathSync(a) === fs.realpathSync(b);
}
